version: 1.0.0

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=core'
      - 'POSTGRES_PASSWORD=1314246'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
